// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Web from "solid-js/web";

Web.render((function (param) {
        return App.createElement(/* [] */0, undefined);
      }), Belt_Option.getExn(Caml_option.nullable_to_opt(document.getElementById("root"))));

export {
  
}
/*  Not a pure module */
